"""Cross-reference enhancer.

Rewrites in-prose mentions of figures, sections, and bibliography entries as
markdown links pointing at anchors in the same document.

Three transformations are layered:

1. **Anchor injection** — explicit ``<a id="..."></a>`` tags are inserted
   immediately above each figure marker and each bibliography entry. Section
   headings rely on the implicit slug autogenerated by markdown renderers, so
   no extra HTML is emitted for them. (Tests verify both behaviours.)
2. **Skip-range computation** — caption blocks (``Fig. N | ...``) and the
   bibliography region (everything below a ``## References`` heading) are
   identified up-front. Mentions inside those ranges are *not* rewritten,
   since linking from a caption to itself is noise and the bibliography list
   already lives at its own anchor.
3. **Mention rewriting** — a single regex pass per pattern (figures, sections,
   citations) replaces matches with ``[label](#anchor)``. Citations are
   expanded so ``[12,13,14]`` and ``[12-14]`` each produce three separate
   links.

The enhancer is safe on any combination of inputs: documents with no figures,
no sections, or no parsed references all degrade to a no-op.
"""

from __future__ import annotations

import re

from pdf2md.document import Document

# --- Regex patterns ------------------------------------------------------

# Figure markers: ``![alt text](id_or_path)``
_FIGURE_MARKER_RE = re.compile(r"^\s*!\[(?P<alt>[^\]]*)\]\((?P<id>[^)]+)\)\s*$")

# Figure mention patterns. We capture an optional panel suffix so that
# ``Fig. 3a`` keeps the ``a`` in link text while still anchoring at fig-3.
# Order matters: ``Extended Data Fig.`` must be tried first so the simpler
# ``Fig.`` pattern doesn't shadow it.
_FIGURE_MENTION_RES: list[tuple[re.Pattern[str], bool, str]] = [
    (
        re.compile(
            r"\bExtended\s+Data\s+Fig\.?\s+(\d+)([a-z](?:[,–-][a-z])*)?\b"
        ),
        True,
        "Extended Data Fig.",
    ),
    (
        re.compile(r"\bFigure\s+(\d+)([a-z](?:[,–-][a-z])*)?\b"),
        False,
        "Figure",
    ),
    (
        re.compile(r"\bFig\.\s+(\d+)([a-z](?:[,–-][a-z])*)?\b"),
        False,
        "Fig.",
    ),
]

# Section mention: ``Section 4.2`` (capture the dotted number).
_SECTION_MENTION_RE = re.compile(r"\bSection\s+(\d+(?:\.\d+)*)\b")

# Citation list. Single number (``[3]``) is included; ranges and lists may
# combine commas, en-dashes, and hyphens with optional whitespace.
_CITATION_RE = re.compile(r"\[(\d+(?:\s*[,–-]\s*\d+)*)\]")

# Caption opener used to identify both stand-alone caption blocks and the
# alt-text inside figure markers.
_CAPTION_HEADER_RE = re.compile(
    r"^\s*(?:Extended\s+Data\s+)?Fig\.?\s*\d+\s*\|", re.IGNORECASE
)

# Markdown ``## References`` / ``## Bibliography`` heading.
_REFERENCES_HEADING_RE = re.compile(
    r"^\s*#{1,4}\s+(References|Bibliography)\s*$", re.IGNORECASE
)

# Numbered bibliography entry openers: ``[12] ...`` or ``12. ...``.
_BIBLIO_BRACKET_RE = re.compile(r"^\s*\[(\d+)\]\s+\S")
_BIBLIO_DOTTED_RE = re.compile(r"^\s*(\d+)\.\s+\S")


# --- Public entry point --------------------------------------------------


def add_cross_references(markdown: str, doc: Document) -> str:
    """Rewrite figure / section / citation mentions as markdown links.

    Idempotent and cheap. Safe on documents with no figures, no sections, or
    no parsed References section — degrades to a no-op rather than raising.
    """
    if not markdown:
        return markdown

    lines = markdown.split("\n")

    figure_anchors = _figure_anchors(doc)
    section_anchors = _section_anchors(doc)
    biblio_lines = _bibliography_line_numbers(lines)

    # Inject anchors first so subsequent rewriting sees a consistent layout.
    lines = _inject_figure_anchors(lines, figure_anchors)
    lines, biblio_lines = _inject_bibliography_anchors(lines, biblio_lines)

    skip_ranges = _compute_skip_ranges(lines)

    rewritten = [
        line
        if idx in skip_ranges
        else _rewrite_line(
            line,
            figure_anchors=figure_anchors,
            section_anchors=section_anchors,
            biblio_lines=biblio_lines,
        )
        for idx, line in enumerate(lines)
    ]

    return "\n".join(rewritten)


# --- Anchor index construction -------------------------------------------


def _figure_anchors(doc: Document) -> dict[tuple[int, bool], str]:
    """Return ``{(figure_number, is_extended): anchor_slug}``.

    Prefers ``doc.figure_index`` because it carries the parsed figure number
    and the ``is_extended`` flag explicitly. Falls back to ``doc.figures``
    using the trailing digit on the figure id.
    """
    anchors: dict[tuple[int, bool], str] = {}

    for entry in getattr(doc, "figure_index", []) or []:
        if entry.figure_number is None:
            continue
        key = (entry.figure_number, bool(entry.is_extended))
        anchors.setdefault(key, _figure_slug(entry.figure_number, entry.is_extended))

    if not anchors:
        for fig in getattr(doc, "figures", []) or []:
            num = _trailing_int(fig.id)
            if num is None:
                continue
            anchors.setdefault((num, False), _figure_slug(num, False))

    return anchors


def _figure_slug(number: int, is_extended: bool) -> str:
    return f"extended-data-fig-{number}" if is_extended else f"fig-{number}"


def _section_anchors(doc: Document) -> dict[str, str]:
    """Return ``{section_number: heading_slug}`` for numbered sections.

    Only sections whose title starts with a dotted number (``4.2 Methods``)
    are indexed — those are the ones a reader can write ``Section 4.2`` for.
    """
    anchors: dict[str, str] = {}
    for section in getattr(doc, "sections", []) or []:
        match = re.match(r"^(\d+(?:\.\d+)*)\.?\s+(.+)$", section.title.strip())
        if not match:
            continue
        number = match.group(1)
        anchors.setdefault(number, _heading_slug(section.title))
    return anchors


def _heading_slug(title: str) -> str:
    """Slug a heading the way GitHub-Flavored Markdown does.

    Lowercases, replaces whitespace with hyphens, and drops anything that
    isn't alphanumeric or a hyphen. The result is what most renderers
    auto-generate, so explicit anchors are unnecessary for headings.
    """
    slug = title.strip().lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"\s+", "-", slug).strip("-")
    return slug


def _bibliography_line_numbers(lines: list[str]) -> dict[int, str]:
    """Find numbered references under a ``## References`` heading.

    Returns ``{ref_number: anchor_slug}``. Detects two common formats:
    ``[12] Author...`` and ``12. Author...``. Bare digit lines (e.g. page
    numbers) are ignored — the regexes require non-whitespace following the
    number marker.
    """
    refs: dict[int, str] = {}
    in_references = False

    for line in lines:
        if _REFERENCES_HEADING_RE.match(line):
            in_references = True
            continue
        # Stop at the next top-level heading (## or #).
        if in_references and re.match(r"^\s*#{1,4}\s+\S", line):
            heading_match = re.match(r"^\s*#{1,4}\s+(.+)$", line)
            if heading_match and not _REFERENCES_HEADING_RE.match(line):
                break
        if not in_references:
            continue

        m = _BIBLIO_BRACKET_RE.match(line) or _BIBLIO_DOTTED_RE.match(line)
        if m:
            num = int(m.group(1))
            refs.setdefault(num, f"ref-{num}")

    return refs


# --- Anchor injection ----------------------------------------------------


def _inject_figure_anchors(
    lines: list[str], figure_anchors: dict[tuple[int, bool], str]
) -> list[str]:
    """Insert ``<a id="..."></a>`` directly above each figure marker.

    Anchors are derived from the alt text (``![Fig. 1 | ...](fig1)``) so the
    injected slug always matches the rewriter's expectations. Markers whose
    alt text doesn't carry a parseable label are skipped.
    """
    if not figure_anchors:
        return lines

    out: list[str] = []
    for line in lines:
        marker = _FIGURE_MARKER_RE.match(line)
        if marker:
            label = _parse_figure_label(marker.group("alt"))
            if label is not None:
                anchor = figure_anchors.get(label)
                # Avoid double-injecting if a previous run already added it.
                already = bool(
                    out and re.match(rf'^\s*<a id="{re.escape(anchor or "")}"', out[-1])
                )
                if anchor and not already:
                    out.append(f'<a id="{anchor}"></a>')
        out.append(line)
    return out


def _inject_bibliography_anchors(
    lines: list[str], biblio_lines: dict[int, str]
) -> tuple[list[str], dict[int, str]]:
    """Prefix each numbered reference entry with an inline anchor.

    Inserting an inline ``<a id="ref-N"></a>`` keeps the visible numbering
    intact. Indexes in ``biblio_lines`` need no remapping — we mutate lines
    in place rather than adding new ones.
    """
    if not biblio_lines:
        return lines, biblio_lines

    in_references = False
    out: list[str] = []
    for line in lines:
        if _REFERENCES_HEADING_RE.match(line):
            in_references = True
            out.append(line)
            continue
        if in_references and re.match(r"^\s*#{1,4}\s+\S", line) and not _REFERENCES_HEADING_RE.match(line):
            in_references = False
        if in_references:
            m = _BIBLIO_BRACKET_RE.match(line) or _BIBLIO_DOTTED_RE.match(line)
            if m:
                num = int(m.group(1))
                anchor = biblio_lines.get(num)
                if anchor and f'id="{anchor}"' not in line:
                    line = f'<a id="{anchor}"></a>{line}'
        out.append(line)
    return out, biblio_lines


def _parse_figure_label(alt: str) -> tuple[int, bool] | None:
    match = re.match(
        r"^\s*(Extended\s+Data\s+)?Fig\.?\s*(\d+)\b", alt, re.IGNORECASE
    )
    if not match:
        match = re.match(r"^\s*Figure\s+(\d+)\b", alt, re.IGNORECASE)
        if not match:
            return None
        return (int(match.group(1)), False)
    return (int(match.group(2)), bool(match.group(1)))


# --- Skip-range computation ----------------------------------------------


def _compute_skip_ranges(lines: list[str]) -> set[int]:
    """Indexes of lines that must not be rewritten.

    Rewriting inside captions or inside the bibliography list is undesirable:
    captions describe the figure they're attached to, and reference entries
    already sit at their own anchor.
    """
    skip: set[int] = set()

    in_caption = False
    for idx, line in enumerate(lines):
        if _FIGURE_MARKER_RE.match(line):
            skip.add(idx)
            continue
        if _CAPTION_HEADER_RE.match(line):
            in_caption = True
            skip.add(idx)
            continue
        if in_caption:
            stripped = line.strip()
            if not stripped:
                in_caption = False
                continue
            if re.match(r"^\s*#{1,4}\s+", line) or _CAPTION_HEADER_RE.match(line):
                in_caption = False
                # Don't break — fall through to the heading skip logic below.
            else:
                skip.add(idx)
                continue

    in_references = False
    for idx, line in enumerate(lines):
        if _REFERENCES_HEADING_RE.match(line):
            in_references = True
            continue
        if in_references and re.match(r"^\s*#{1,4}\s+\S", line) and not _REFERENCES_HEADING_RE.match(line):
            in_references = False
            continue
        if in_references:
            skip.add(idx)

    return skip


# --- Rewriting -----------------------------------------------------------


def _rewrite_line(
    line: str,
    *,
    figure_anchors: dict[tuple[int, bool], str],
    section_anchors: dict[str, str],
    biblio_lines: dict[int, str],
) -> str:
    """Apply all three rewrite passes to a single line.

    Order: figures, then sections, then citations. Each pass is a single
    ``re.sub`` over the line — total work is O(line length) per pattern, so
    O(n) overall for the markdown.
    """
    if figure_anchors:
        for pattern, is_extended, label_word in _FIGURE_MENTION_RES:
            line = pattern.sub(
                lambda m, ext=is_extended, lw=label_word: _replace_figure(
                    m, figure_anchors, ext, lw
                ),
                line,
            )

    if section_anchors:
        line = _SECTION_MENTION_RE.sub(
            lambda m: _replace_section(m, section_anchors), line
        )

    if biblio_lines:
        line = _CITATION_RE.sub(
            lambda m: _replace_citation(m, biblio_lines), line
        )

    return line


def _replace_figure(
    match: re.Match[str],
    figure_anchors: dict[tuple[int, bool], str],
    is_extended: bool,
    label_word: str,
) -> str:
    number = int(match.group(1))
    panel = match.group(2) or ""
    anchor = figure_anchors.get((number, is_extended))
    if not anchor:
        return match.group(0)
    text = f"{label_word} {number}{panel}"
    return f"[{text}](#{anchor})"


def _replace_section(
    match: re.Match[str], section_anchors: dict[str, str]
) -> str:
    number = match.group(1)
    anchor = section_anchors.get(number)
    if not anchor:
        return match.group(0)
    return f"[Section {number}](#{anchor})"


def _replace_citation(
    match: re.Match[str], biblio_lines: dict[int, str]
) -> str:
    """Expand a citation group into a comma-joined list of links.

    ``[12-14]`` -> three links; ``[12,13]`` -> two links; ``[12]`` -> one
    link. If *any* number in the group is missing from the bibliography we
    leave the whole group untouched — partial expansion would produce a
    confusing mix of plain text and links.
    """
    numbers = _expand_citation_group(match.group(1))
    if not numbers:
        return match.group(0)
    if any(num not in biblio_lines for num in numbers):
        return match.group(0)
    parts = [f"[{num}](#{biblio_lines[num]})" for num in numbers]
    return "[" + ",".join(parts) + "]"


def _expand_citation_group(content: str) -> list[int]:
    """Parse ``"12,13,14"`` or ``"12-14"`` (or mixed) into ``[12, 13, 14]``."""
    numbers: list[int] = []
    for chunk in re.split(r"\s*,\s*", content):
        if not chunk:
            continue
        range_match = re.match(r"^\s*(\d+)\s*[-–]\s*(\d+)\s*$", chunk)
        if range_match:
            start, end = int(range_match.group(1)), int(range_match.group(2))
            if start > end or end - start > 50:  # sanity cap
                return []
            numbers.extend(range(start, end + 1))
            continue
        single = re.match(r"^\s*(\d+)\s*$", chunk)
        if single:
            numbers.append(int(single.group(1)))
            continue
        return []  # unparseable chunk — bail out on the whole group
    return numbers


# --- Helpers -------------------------------------------------------------


def _trailing_int(text: str) -> int | None:
    match = re.search(r"(\d+)$", text)
    return int(match.group(1)) if match else None
